version: "2"

formatters:
  enable:
    - gofumpt

linters:
  default: all
  disable:
    - prealloc # we're not that performance critical
    - noinlineerr # I like inline error handling
    - err113 # we use fmt.Errorf("context: %w")
    - testpackage # we're using internal packages for unit tests

    # maybe enable in the future
    - depguard # consider enabling when architecture stabilizes
    - paralleltest # consider enabling if tests become too slow

    # these don't check behavior, so relatively safe to disable
    - wsl # deprecated
    - wsl_v5
    - nlreturn
    - lll

  settings:
    varnamelen:
      ignore-decls:
        - i int
        - n int
        - sb *sandbox.Sandbox
        - wg sync.WaitGroup
        - wg *sync.WaitGroup
        - w http.ResponseWriter
        - r *http.Request
        - sb strings.Builder
        - s *scenario
        - ok bool

    exhaustive:
      default-signifies-exhaustive: true

    exhaustruct:
      exclude:
        - '.+/cobra\.Command$'
        - '(net|net/http|crypto/tls|syscall)\..+' # stdlib structs are well-known, well-behaved, and stable
        - '(golang.org/x/sys/unix)\..+' # same as above

    goconst:
      ignore-tests: true

    mnd:
      ignored-numbers:
        - "3"

  exclusions:
    rules:
      - linters:
          - varnamelen
        path: '(.+)_test\.go'
        text: "'tt'"

      - linters:
          - gochecknoglobals
        path: 'export_test\.go'

      - linters:
          - goconst
          - noctx
        path: '(.+)_test\.go'
